### ISSUE TITLE
dav1d_123's profile entire rescan

### ISSUE THREAD

**Issue by PolySensei** [Ragowit/psn100#6559]
Don't have any hidden trophies and never had: https://psn100.net/player/dav1d_123

**Comment by Ragowit** [comment]
Thanks for letting me know. I recently found out that some users with large amount of games might have been mistagged as hidden because the scanner ended too early and thus not scanning all the games (therefor thinking the player had hid some trophies).

You're in the scan queue for a rescan, but there are a couple of other players in front of you so it might take a while.

**Comment by Ragowit** [comment]
Profile successfully rescanned and no longer tagged with hidden trophies.
